services:
  - type: worker
    name: forum-guard
    runtime: python
    plan: starter # NOTE: This is a paid plan, as required for workers.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    disk:
      name: forum-guard-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_PATH
        value: /data/database.sqlite3
      - key: LOG_PATH
        value: /data/bot.log